BOOKS AUD:

CREATE TABLE BOOKS_AUD (

                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT, EVENT_DATE DATETIME NOT NULL, EVENT_TYPE VARCHAR(10) DEFAULT NULL, BOOK_ID INT(11) NOT NULL, OLD_BOOK_ID INT(11), TITLE VARCHAR(255), PUBYEAR INT(11), PRIMARY KEY (EVENT_ID)

);

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS FOR EACH ROW BEGIN

    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, TITLE, PUBYEAR)

        VALUE(CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR); END $$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS FOR EACH ROW BEGIN

    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)

        VALUE(CURTIME(), "DELETE", OLD.BOOK_ID); END $$

DELIMITER ;

DELETE FROM BOOKS WHERE BOOK_ID = 23; DELIMITER $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS FOR EACH ROW BEGIN

    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_BOOK_ID)

        VALUE(CURTIME(), "UPDATE", NEW.BOOK_ID, OLD.BOOK_ID); END $$

DELIMITER ;

UPDATE BOOKS SET BOOK_ID = 22 WHERE BOOK_ID = 66;

READER AUD:

CREATE TABLE READERS_AUD (

                             EVENT_ID INT(11) NOT NULL AUTO_INCREMENT, EVENT_DATE DATETIME NOT NULL, EVENT_TYPE VARCHAR(10) DEFAULT NULL, READER_ID INT(11) NOT NULL, OLD_READER_ID INT(11), NEW_FIRSTNAME VARCHAR(255), OLD_FIRSTNAME VARCHAR(255), NEW_LASTNAME VARCHAR(255), OLD_LASTNAME VARCHAR(255), NEW_PESELID VARCHAR(255), OLD_PESELID VARCHAR(255), PRIMARY KEY (EVENT_ID)

);

DELIMITER $$

CREATE TRIGGER READER_INSERT AFTER INSERT ON READERS FOR EACH ROW BEGIN

    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID) VALUE(CURTIME(), "INSERT", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW_PESELID); END $$

DELIMITER ;

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESELID) VALUES ('Mike', 'Bike', '99012217938');

DELIMITER $$

CREATE TRIGGER READER_DELETE AFTER DELETE ON READERS FOR EACH ROW BEGIN

    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)

        VALUE(CURTIME(), "DELETE", OLD.READER_ID); END $$

DELIMITER ;

DELETE FROM READERS WHERE READER_ID = 6;

DELIMITER $$

CREATE TRIGGER READER_UPDATE AFTER UPDATE ON READERS FOR EACH ROW BEGIN

    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID,NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID, OLD_FIRSTNAME, OLD_LASTNAME, OLD_PESELID)

        VALUE(CURTIME(), "UPDATE", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID ,OLD.FIRSTNAME, OLD.LASTNAME, OLD.PESELID); END $$

DELIMITER ; UPDATE READERS SET FIRSTNAME = 'Sam' WHERE FIRSTNAME = 'Mike';